export { default as Home} from "./Home"
export { default as About} from "./About"
export { default as Products} from "./Products"
export { default as Cart} from "./Cart"
export { default as OrderHistory} from "./OrderHistory"
export {default as SingleProduct} from "./SingleProduct"
export {default as ErrorPage} from "./ErrorPage"